server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social-app
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB